version: '3'
services:
    transmission:
        image: haugene/transmission-openvpn
        user: root
        hostname: transmission
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun
        ports:
            - "9321:9091"
            - "8888:8888"
        dns:
            - 8.8.8.8
            - 8.8.4.4
        volumes:
            - '/changan/docker/config/transmission/:/config'
            - '/changan/docker/downloads/:/data'
            - '/etc/localtime:/etc/localtime:ro'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_USERNAME=p3442358
            - OPENVPN_PASSWORD=Reznor666
            - OPENVPN_CONFIG=US Las Vegas
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - LOCAL_NETWORK=192.168.0.0/16
            - TZ=America/Boise
            - PUID=0
            - VIRTUAL_HOST="tm.kingmob.xyz"
    plex:
        image: linuxserver/plex
        user: root
        network_mode: "host"
        # ports:
        #     - '32400:32400'
        #     - '32400:32400/udp'
        #     - '32469:32469'
        #     - '32469:32469/udp'
        #     - '9393:5353/udp'
        #     - '1900:1900/udp'
        volumes:
            - '/changan/docker/config/plex/:/config'
            - '/mnt/docker/downloads/:/downloads'
            - '/mnt/media/Movies/:/movies'
            - '/mnt/media/TV/:/tv'
            - '/mnt/media/Music/:/music'
            - '/mnt/media/Books/:/books'
            - '/mnt/media/Comics/:/comics'
        environment:
            TZ: America/Boise
            VERSION: latest
